### ISSUE TITLE
关于粘性事件👍 

### ISSUE THREAD

**Issue by ChaosOctopus** [o0o0oo00/Airport#1]
感觉简易版也可以缓存一个map 来支持粘性事件

**Comment by o0o0oo00** [comment]
> 感觉简易版也可以缓存一个map 来支持粘性事件

就是支持粘性事件的！

粘性事件意思就是说，后来订阅的***观察者***仍然可以接收到之前***被观察者***发送的事件，现在的AnyDoor就是支持粘性事件，另一个Airport是非粘性事件，就是说后来订阅的***观察者***不会接收到之前***被观察者***发送的事件，只能接收在订阅之后发送的事件

 (●´З｀●)
